name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install --system -r requirements.txt
      - name: Lint with black
        run: black --check src tests
      - name: Check pipeline script
        run: PYTHONPATH=. python -m src.pipelines.pipeline --help || true
      - name: Run tests
        run: pytest tests
      - name: Check API startup
        run: |
          timeout 10 python -m src.api.main
          kill %1
