name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Lint with Black      
        run: |
        black src tests
        black --check src tests

      - name: Preprocess data
        run: python -m src.data.preprocess

      - name: Train model
        run: python -m src.models.train

      - name: Evaluate model
        run: python -m src.models.evaluate

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: model-evaluation-report
          path: models/model_evaluation_report.md

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: pytest

      - name: Verify API startup
        run: timeout 10 python -m src.api.main || true
