name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Lint with black
        run: |
          source .venv/bin/activate
          black --check src tests
      - name: Check pipeline script
        run: |
          source .venv/bin/activate
          python -m src.pipelines.pipeline || true
      - name: Run tests
        run: |
          source .venv/bin/activate 
          pytest tests
      - name: Check API startup
        run: |
          source .venv/bin/activate
          timeout 10 python -m src.api.main || true
          kill %1
